FROM node:21-alpine3.19

WORKDIR /usr/src/app

COPY package.json yarn.lock turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN yarn install

# generating prisma client
RUN yarn run db:generate

# Can you filter the build down to just one app?
RUN yarn run build

CMD ["yarn", "run", "start-user-app"]